name: JS Actions

on: [push]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-custom-action
        uses: ./.github/actions/hello-world
        
      - name: joke-custom-action
        uses: ./.github/actions/joke-action
